config/routes.rb
Rails.application.routes.draw do
  get 'services/index'
  get 'services/show'
  get 'about/index'
  mount Ckeditor::Engine => '/ckeditor'
  get 'types/show'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'comments/new'
  get 'categories/new'
  get 'categories/create'
  get 'categories/edit'
  get 'categories/update'
  get 'categories/index'
  get 'categories/show'
  get 'categories/destroy'
  devise_for :users
  get 'posts/new'
  get 'posts/create'
  get 'posts/edit'
  get 'posts/update'
  get 'posts/index'
  get 'posts/show'
  get 'posts/destroy'
  get 'videos/new'
  get 'videos/create'
  get 'videos/edit'
  get 'videos/update'
  get 'videos/index'
  get 'videos/show'
  get 'videos/destroy'
  get 'audios/new'
  get 'audios/create'
  get 'audios/edit'
  get 'audios/update'
  get 'audios/index'
  get 'audios/show'
  get 'audios/destroy'
  get 'contact' => 'contacts#new', :as => 'contact'
  get 'contacts/create'
  get 'about' => 'about#index', :as => 'about'
  get 'home' => 'home#index', as: 'home'

  resources :contacts, :audios, :videos, :posts, :categories, :comments, :services
  resources :types, only: [:show]

  resources :posts do
    resources :comments
  end
  root 'home#index'
  
  match "*path", to: "videos#catch_404", via: :all
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/audio.rb
class Audio < ApplicationRecord
  belongs_to :user
  belongs_to :type
  #validates picture to uplaod
  has_attached_file :coverpicture, styles: { medium: "300x300>", thumb: "100x100#" } #default_url: "/images/:style/missing.png"
  validates_attachment_content_type :coverpicture, content_type: /\Aimage\/.*\Z/

  #valides audios to upload
  has_attached_file :song_audio 
  validates_attachment :song_audio,
  :content_type => {:content_type => ["audio/mpeg", "audio/mp3"]},
  :file_type => {:matches => [/mp3\Z/]}

  validates_presence_of :title
  validates_presence_of :artist


  def self.search(query)
    where("artist like ? OR title like ?","%#{query}%", "%#{query}%")
end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts


    validates_uniqueness_of :name    
    validates_presence_of :name
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/contact.rb
class Contact < ApplicationRecord

    validates_presence_of :name
    validates_presence_of :email
    validates_presence_of :message
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :comments
    
    has_attached_file :coverpicture, styles: { medium: "300x300>", thumb: "100x100#" } #default_url: "/images/:style/missing.png"
    validates_attachment_content_type :coverpicture, content_type: /\Aimage/

    validates_presence_of :coverpicture
    validates_presence_of :title
    validates_presence_of :body

    def self.search(query)
        where("body like ? OR title like ?","%#{query}%", "%#{query}%")
    end
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :audios
    has_many :videos
    validates :name, presence: true, uniqueness: true
    
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/models/video.rb
class Video < ApplicationRecord
    belongs_to :user
    belongs_to :type

    validates_presence_of :song_title
    validates_presence_of :singer_name
    validates_presence_of :youtube_link
    validates_presence_of :song_title

    has_attached_file :coverpicture, styles: { medium: "300x300>", thumb: "100x100#" } #default_url: "/images/:style/missing.png"
    validates_attachment_content_type :coverpicture, content_type: /\Aimage\/.*\Z/
    def self.search(query)
        where("song_title like ? OR singer_name like ?","%#{query}%", "%#{query}%")
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController

  before_action :authenticate_user!, only: [:edit, :update, :index, :new, :destory]

  def show
    @type = Type.find(params[:id])
    @videos = @type.videos.all.order('created_at DESC').page(params[:page]).per(20)
    @audios = @type.audios.all.order('created_at DESC').page(params[:page]).per(20)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/types/show.html.erb
<div class="recent-upload text-center">
    <h4><%= @type.name %></h4>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <% if @audios.exists? %>
                <h3 class="page-header"> RELATED AUDIOS</h3>
                  <% @audios.each do |song|%>
                     <div class="col-md-6">
                        <div class="panel panel-info">
                            <div class="panel-body">
                                <%if song.coverpicture.present?%>
                                    <%= image_tag  "#{song.coverpicture}", class:'thumbnail', width:'220px', height:'180px' %>
                                <%else%>
                                    <%= image_tag  "img/image2.jpg", class:'thumbnail', width:'220px', height:'180px' %>
                                <% end %>
                                    <li><strong>Song name: </strong><%= song.title%></li>
                                    <li><strong>Artist: </strong><%= song.artist %></li>
                                    <li><strong>Upload on: </strong> <%= song.created_at.to_time.strftime('%b %e, %Y ') %></li>
                                    
                                    <%= link_to  "Play", audio_path(song), class:'glyphicon glyphicon-ok btn btn-success' %>
                            </div>
                        </div> 
                     </div>
                  <% end %>          
            <%else%>
                <p>No audio published yet, come back very soon!!</p>
            <% end %>
            <!-- pagination -->
            <%= paginate @audios, :theme => 'twitter-bootstrap-3' %>            
        </div><!-- End of Audios by type -->
        <div class="col-md-6">
          <%if @videos.exists? %>
                <h3 class="page-header"> RELATED VIDEOS</h3>                
                  <% @videos.each do |song|%>
                     <div class="col-md-6">
                        <div class="panel panel-info">
                            <div class="panel-body">
                                <%if song.youtube_link.present?%>
                                
                               <iframe width="230" height="200" src="https://www.youtube.com/embed/<%= song.youtube_link %>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                                <%else%>
                                    <%= image_tag  "img/image2.jpg", class:'thumbnail', width:'30%' %>
                                <% end %>
                                    <li><strong>Song name: </strong><%= song.song_title%></li>
                                    <li><strong>Artist: </strong><%= song.singer_name %></li>
                                    <li><strong>Upload on:</strong><%= song.created_at.to_time.strftime('%b %e, %Y ') %></li>
                                    
                                    <%= link_to  "View", video_path(song), class:'glyphicon glyphicon-ok btn btn-success' %>
                            </div>
                        </div> 
                     </div>
                  <% end %>
                 <!-- pagination -->
                <%= paginate @videos, :theme => 'twitter-bootstrap-3' %>        
            <%else%>
                <p>No Video published yet, come back very soon!!</p>
            <% end %>  
        </div><!-- End of videos by type -->
    </div>
</div>