config/routes.rb
Rails.application.routes.draw do
  get 'services/index'
  get 'services/show'
  get 'about/index'
  mount Ckeditor::Engine => '/ckeditor'
  get 'types/show'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'comments/new'
  get 'categories/new'
  get 'categories/create'
  get 'categories/edit'
  get 'categories/update'
  get 'categories/index'
  get 'categories/show'
  get 'categories/destroy'
  devise_for :users
  get 'posts/new'
  get 'posts/create'
  get 'posts/edit'
  get 'posts/update'
  get 'posts/index'
  get 'posts/show'
  get 'posts/destroy'
  get 'videos/new'
  get 'videos/create'
  get 'videos/edit'
  get 'videos/update'
  get 'videos/index'
  get 'videos/show'
  get 'videos/destroy'
  get 'audios/new'
  get 'audios/create'
  get 'audios/edit'
  get 'audios/update'
  get 'audios/index'
  get 'audios/show'
  get 'audios/destroy'
  get 'contact' => 'contacts#new', :as => 'contact'
  get 'contacts/create'
  get 'about' => 'about#index', :as => 'about'
  get 'home' => 'home#index', as: 'home'

  resources :contacts, :audios, :videos, :posts, :categories, :comments, :services
  resources :types, only: [:show]

  resources :posts do
    resources :comments
  end
  root 'home#index'
  
  match "*path", to: "videos#catch_404", via: :all
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/audio.rb
class Audio < ApplicationRecord
  belongs_to :user
  belongs_to :type
  #validates picture to uplaod
  has_attached_file :coverpicture, styles: { medium: "300x300>", thumb: "100x100#" } #default_url: "/images/:style/missing.png"
  validates_attachment_content_type :coverpicture, content_type: /\Aimage\/.*\Z/

  #valides audios to upload
  has_attached_file :song_audio 
  validates_attachment :song_audio,
  :content_type => {:content_type => ["audio/mpeg", "audio/mp3"]},
  :file_type => {:matches => [/mp3\Z/]}

  validates_presence_of :title
  validates_presence_of :artist


  def self.search(query)
    where("artist like ? OR title like ?","%#{query}%", "%#{query}%")
end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts


    validates_uniqueness_of :name    
    validates_presence_of :name
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/contact.rb
class Contact < ApplicationRecord

    validates_presence_of :name
    validates_presence_of :email
    validates_presence_of :message
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :comments
    
    has_attached_file :coverpicture, styles: { medium: "300x300>", thumb: "100x100#" } #default_url: "/images/:style/missing.png"
    validates_attachment_content_type :coverpicture, content_type: /\Aimage/

    validates_presence_of :coverpicture
    validates_presence_of :title
    validates_presence_of :body

    def self.search(query)
        where("body like ? OR title like ?","%#{query}%", "%#{query}%")
    end
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :audios
    has_many :videos
    validates :name, presence: true, uniqueness: true
    
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/models/video.rb
class Video < ApplicationRecord
    belongs_to :user
    belongs_to :type

    validates_presence_of :song_title
    validates_presence_of :singer_name
    validates_presence_of :youtube_link
    validates_presence_of :song_title

    has_attached_file :coverpicture, styles: { medium: "300x300>", thumb: "100x100#" } #default_url: "/images/:style/missing.png"
    validates_attachment_content_type :coverpicture, content_type: /\Aimage\/.*\Z/
    def self.search(query)
        where("song_title like ? OR singer_name like ?","%#{query}%", "%#{query}%")
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  before_action :authenticate_user!, only: [:edit, :new, :create, :update, :destory]
  before_action :index, only: [:index, :show]
  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    if @video.save 
      redirect_to videos_path, :notice => 'Video published'
    else
      render 'new'
    end
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])
    if @video.update(video_params)
      redirect_to video_path(@video), notice: 'All changes have been saved'
    else
      render 'edit'
    end
  end

  def index
    if params[:search]
      @videos = Video.search(params[:search]).all.order('created_at DESC')
      @types = Type.all
    
    else
      @videos = Video.all.order('created_at DESC')
      @types = Type.all
    end
  end

  def show
    @video = Video.find(params[:id])
    if @video
      @artists = Video.where("singer_name = ?", @video.singer_name).page(params[:page]).per(5)
    end
  end

  def destroy
  end
  
  def catch_404
    raise ActionController::RoutingError.new(params[:path])
    raise ActiveRecord::RecordNotFound.new(params[:path])
  end
  private
  def video_params
    params.require(:video).permit(:song_title, :singer_name, :rabel_name, :type_id, :user_id, :youtube_link)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/edit.html.erb
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
       <h2 class="">
        <div class="recent-upload">
            <h4><span class="glyphicon glyphicon-upload"></span>&nbsp;EDIT VIDEO &nbsp; "<span ><%= @video.song_title%></span>"</h4>
        </div>
        </h2>
       <%= form_for( @video) do |f| %>
       <% if @video.errors%>
        <% @video.errors.full_messages.each do |msg|%>
         <div class="alert alert-danger"><%= msg %></div>
        <%end%>
        <%end%>
       <div class="form-group">
           <%= f.label :song_title%>
           <%= f.text_field :song_title, class:'form-control'%>
       </div>
        <div class="form-group">
           <%= f.label :singer_name%>
           <%= f.text_field :singer_name, class:'form-control'%>
       </div>
       <div class="form-group">
           <%= f.label :category%>
           <%= f.select :type_id, Type.all.collect {|x|[x.name, x.id]}, {:include_blank => 'Select Category'}, class:'form-control'%>
       </div>
        <div class="form-group">
           <%= f.label :rabel_name %>
           <%= f.text_field :rabel_name, class:'form-control'%>
       </div>
        <div class="form-group">
           <%= f.label :youtube_link, class:'glyphicon glyphicon-link' %>
           <%= f.text_field :youtube_link, class:'form-control'%>
       </div>
       <div class="form-group">
           <%= f.text_field :user_id, class:'hidden', value:"#{current_user.id}"%>
       </div>
       <div class="form-group">
        <%= f.submit 'Publish Video', class:'btn btn-primary'%>
        <%= link_to  "Cancel", videos_path, class:'btn btn-default' %>
       </div>
       <% end %>
    </div>
    <div class="col-md-4"></div>
</div>

app/views/videos/index.html.erb
<h2 class="page-header">
  <% if current_user%>
    <%= link_to  "Upload ", new_video_path, class:'btn btn-info' %>
  <% end %>
</h2>
<div class="row">
        <div class="col-md-10">
            <div class="recent-upload">
                <h4>RECENT UPLOADED VIDEOS</h4>
            </div>
            <%if @videos.exists? %>
                 <div class="row">
                  <% @videos.each do |song|%>
                     <div class="col-md-4">
                        <div class="panel panel-info">
                            <div class="panel-body">
                                <%if song.youtube_link.present?%>
                               <iframe width="100%" height="200" src="https://www.youtube.com/embed/<%= song.youtube_link %>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                                <%else%>
                                    <%= image_tag  "img/image2.jpg", class:'thumbnail', width:'30%' %>
                                <% end %>
                                    <li><strong>Song name: </strong><%= song.song_title%></li>
                                    <li><strong>Artist: </strong><%= song.singer_name %></li>
                                    <li><strong>Upload on:</strong><%= song.created_at.to_time.strftime('%b %e, %Y ') %></li>
                                    
                                    <%= link_to  "View", video_path(song), class:'glyphicon glyphicon-ok btn btn-block btn-success' %>
                            </div>
                        </div> 
                    </div>
                  <% end %>
            <!-- pagination -->
                </div>          
            <%else%>
                <p>No song published yet</p>
            <% end %>
       </div>
       
    <div class="col-md-2" id="category">
        <% if @types.exists%>
            <div class="panel panel-nfio">
                <div class="panel panel-heading">
                    <h4 >Categories</h4>
                </div>
                <div class="panel panel-body">
                   <% @types.each do |type|%>
                        <li class="list-group-item"><%= link_to type.name, type_path(type), class:'glyphicon glyphicon-film'  %></li>
                    <%end%> 
                </div>
            </div>
        <%else%>
        <p>No categories found</p>
        <%end%>
    </div>
</div>

app/views/videos/new.html.erb
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
       <h2 class="">
        <div class="recent-upload">
            <h4><span class="glyphicon glyphicon-upload"></span>&nbsp;Upload New <span id="header">Video</span></h4>
        </div>
        </h2>
       <%= form_for( @video) do |f| %>
       <% if @video.errors%>
        <% @video.errors.full_messages.each do |msg|%>
         <div class="alert alert-danger"><%= msg %></div>
        <%end%>
        <%end%>
       <div class="form-group">
           <%= f.label :song_title%>
           <%= f.text_field :song_title, class:'form-control'%>
       </div>
        <div class="form-group">
           <%= f.label :singer_name%>
           <%= f.text_field :singer_name, class:'form-control'%>
       </div>
       <div class="form-group">
           <%= f.label :category%>
           <%= f.select :type_id, Type.all.collect {|x|[x.name, x.id]}, {:include_blank => 'Select Category'}, class:'form-control'%>
       </div>
        <div class="form-group">
           <%= f.label :rabel_name %>
           <%= f.text_field :rabel_name, class:'form-control'%>
       </div>
        <div class="form-group">
           <span class="ytb_link">e.g: https://www.youtube.com/watch?v=<i class="ytb_id">C4uUmPkqSpE</i></span>           
           <%= f.label :youtube_link, class:'glyphicon glyphicon-link' %>
           <%= f.text_field :youtube_link, class:'form-control', placeholder:'pick the one in red'%>
       </div>
       <div class="form-group">
           <%= f.text_field :user_id, class:'hidden', value:"#{current_user.id}"%>
       </div>
       <div class="form-group">
        <%= f.submit 'Publish Video', class:'btn btn-primary'%>
        <%= link_to  "Cancel", videos_path, class:'btn btn-default' %>
       </div>
       <% end %>
    </div>
    <div class="col-md-4"></div>
</div>

app/views/videos/show.html.erb
<h2 class="page-header">
  <% if current_user%>
    <% if @video.user_id == current_user.id%>
        <%= link_to  "Edit ", edit_video_path(@video), class:'btn btn-info' %>
    <% end %>
 <% end %>
</h2>
<div class="row">
    <div class="col-md-10">
        <div class="panel panel-default">
            <div class="panel panel-body">
               <%if @video.youtube_link.present?%>
                    <iframe width="100%" height="420" src="https://www.youtube.com/embed/<%= @video.youtube_link %>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                    
                <%else%>
                    <%= image_tag  "img/image2.jpg", class:'thumbnail', width:'40%' %>
                <% end %>
                <div class="panel panel-footer">
                    <li><strong>Category: </strong><%= link_to  @video.type.name, type_path(@video.type.id) %></li>
                    <li><strong>Song name: </strong><%= @video.song_title%></li>
                    <li><strong>Artist: </strong><%= @video.singer_name%></li>
                    <li><strong>Upload by: </strong><%= @video.user.name %></li>
                    <li><strong>Upload on:</strong><%= @video.created_at.to_time.strftime('%A (%b %e, %Y at %H : %M %p)') %></li>  
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-2" id="category">
        <% if @types.exists%>
            <div class="panel panel-nfio">
                <div class="panel panel-heading">
                    <h4 >Category</h4>
                </div>
                <div class="panel panel-body">
                   <% @types.each do |type|%>
                        <li class="list-group-item"><%= link_to type.name, type_path(type), class:'glyphicon glyphicon-film'  %></li>
                    <%end%> 
                </div>
            </div>
        <%else%>
        <p>No categories found</p>
        <%end%>
    </div>
</div> <!-- End of show -->
<div class="row">
    <div class="col-md-10">
       <%if @videos.exists? %>
            <div class="recent-upload">
                <h4>RECENT UPLOADED VIDEOS FROM OUR CHANNEL</h4>
           </div>
            <div class="row">
            <% @videos.each do |song|%>
                <div class="col-md-4">
                <div class="panel panel-info">
                    <div class="panel-body">
                        <%if song.youtube_link.present?%>
                        <iframe width="100%" height="200" src="https://www.youtube.com/embed/<%= song.youtube_link %>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                        <%else%>
                            <%= image_tag  "img/image2.jpg", class:'thumbnail', width:'30%' %>
                        <% end %>
                            <li><strong>Song name: </strong><%= song.song_title%></li>
                            <li><strong>Artist: </strong><%= song.singer_name %></li>
                            <li><strong>Upload on:</strong><%= song.created_at.to_time.strftime('%b %e, %Y ') %></li>
                            
                            <%= link_to  "View", video_path(song), class:'glyphicon glyphicon-ok btn btn-block btn-success' %> 
                    </div>
                </div> 
            </div>
            <% end %>
    <!-- pagination -->
        </div>          
        <%else%>
            <p>No song published yet</p>
        <% end %>
    </div>
    <div class="col-md-2">
       <div class="same-author">
            <div class="panel panel-info">
                <div class="panel panel-heading">
                    <h4 > Related videos</h4>
                </div>
                <% if @artists.exists? %>
                    <% @artists.each do |song| %>
                        <div class="panel-body">
                            <%if song.youtube_link.present?%>
                            <iframe width="100%" height="100" src="https://www.youtube.com/embed/<%= song.youtube_link %>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                            <%else%>
                                <%= image_tag  "img/image2.jpg", class:'thumbnail', width:'30%' %>
                            <% end %>
                                <li><strong>Title: </strong><%= song.song_title%></li>                                
                                <%= link_to  "View", video_path(song), class:'glyphicon glyphicon-ok btn btn-block btn-success' %> 
                        </div> 
                    <% end %>
                <% else %>
                <p>No song with the same artist found!!</p>
                <% end %>
            </div>
        </div>
    </div>
</div>