config/routes.rb
Rails.application.routes.draw do
  get 'services/index'
  get 'services/show'
  get 'about/index'
  mount Ckeditor::Engine => '/ckeditor'
  get 'types/show'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'comments/new'
  get 'categories/new'
  get 'categories/create'
  get 'categories/edit'
  get 'categories/update'
  get 'categories/index'
  get 'categories/show'
  get 'categories/destroy'
  devise_for :users
  get 'posts/new'
  get 'posts/create'
  get 'posts/edit'
  get 'posts/update'
  get 'posts/index'
  get 'posts/show'
  get 'posts/destroy'
  get 'videos/new'
  get 'videos/create'
  get 'videos/edit'
  get 'videos/update'
  get 'videos/index'
  get 'videos/show'
  get 'videos/destroy'
  get 'audios/new'
  get 'audios/create'
  get 'audios/edit'
  get 'audios/update'
  get 'audios/index'
  get 'audios/show'
  get 'audios/destroy'
  get 'contact' => 'contacts#new', :as => 'contact'
  get 'contacts/create'
  get 'about' => 'about#index', :as => 'about'
  get 'home' => 'home#index', as: 'home'

  resources :contacts, :audios, :videos, :posts, :categories, :comments, :services
  resources :types, only: [:show]

  resources :posts do
    resources :comments
  end
  root 'home#index'
  
  match "*path", to: "videos#catch_404", via: :all
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/audio.rb
class Audio < ApplicationRecord
  belongs_to :user
  belongs_to :type
  #validates picture to uplaod
  has_attached_file :coverpicture, styles: { medium: "300x300>", thumb: "100x100#" } #default_url: "/images/:style/missing.png"
  validates_attachment_content_type :coverpicture, content_type: /\Aimage\/.*\Z/

  #valides audios to upload
  has_attached_file :song_audio 
  validates_attachment :song_audio,
  :content_type => {:content_type => ["audio/mpeg", "audio/mp3"]},
  :file_type => {:matches => [/mp3\Z/]}

  validates_presence_of :title
  validates_presence_of :artist


  def self.search(query)
    where("artist like ? OR title like ?","%#{query}%", "%#{query}%")
end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts


    validates_uniqueness_of :name    
    validates_presence_of :name
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/contact.rb
class Contact < ApplicationRecord

    validates_presence_of :name
    validates_presence_of :email
    validates_presence_of :message
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :comments
    
    has_attached_file :coverpicture, styles: { medium: "300x300>", thumb: "100x100#" } #default_url: "/images/:style/missing.png"
    validates_attachment_content_type :coverpicture, content_type: /\Aimage/

    validates_presence_of :coverpicture
    validates_presence_of :title
    validates_presence_of :body

    def self.search(query)
        where("body like ? OR title like ?","%#{query}%", "%#{query}%")
    end
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :audios
    has_many :videos
    validates :name, presence: true, uniqueness: true
    
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/models/video.rb
class Video < ApplicationRecord
    belongs_to :user
    belongs_to :type

    validates_presence_of :song_title
    validates_presence_of :singer_name
    validates_presence_of :youtube_link
    validates_presence_of :song_title

    has_attached_file :coverpicture, styles: { medium: "300x300>", thumb: "100x100#" } #default_url: "/images/:style/missing.png"
    validates_attachment_content_type :coverpicture, content_type: /\Aimage\/.*\Z/
    def self.search(query)
        where("song_title like ? OR singer_name like ?","%#{query}%", "%#{query}%")
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :new, :create, :update, :destory]
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save 
      redirect_to posts_path, :notice => 'Post Published!'
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), notice: 'All changes have been saved'
    else
      render 'edit'
    end
  end

  def index
    if params[:search]
      @posts = Post.search(params[:search]).all.order('created_at DESC')
      @categories = Category.all
    else
      @posts = Post.all.order('created_at DESC')
      @categories = Category.all
    end
  end

  def show
  @post = Post.find(params[:id])
  end

  def destroy
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :coverpicture, :category_id, :user_id)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/posts/edit.html.erb
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
       <h2 class="page-header">
        <div class="recent-upload">
        <h4>EDIT POST <span> &nbsp;"<%= @post.title %></span>"</h4>
    </div>
       </h2>
       <%= form_for( @post) do |f| %>
       <% if @post.errors%>
        <% @post.errors.full_messages.each do |msg|%>
         <div class="alert alert-danger"><%= msg %></div>
        <%end%>
        <%end%>
       <div class="form-group">
           <%= f.label :title%>
           <%= f.text_field :title, class:'form-control'%>
       </div>
       <div class="form-group">
           <%= f.label :category%>
           <%= f.select :category_id, Category.order(:name).collect {|x|[x.name, x.id]}, {:include_blank => 'Select category'}, class:'form-control'%>
       </div>
       <div class="form-group">
           <%= f.text_field :user_id, class:'hidden', value:"#{current_user.id}"%>
       </div>
       <div class="form-group">
           <%= f.label :cover_picture, class:'glyphicon glyphicon-upload' %>
           <%= f.file_field :coverpicture, class:'form-control'%>
           <% if @post.coverpicture.present?%>
            <%= image_tag  "#{@post.coverpicture}", width:'15%' %>
           <% else %>
           <p>Post have no cover image</p>
           <% end %>
       </div>
        <div class="form-group">
           <%= f.label :body%>
           <%= f.cktext_area :body, class:'form-control'%>
       </div>
       <div class="form-group">
        <%= f.submit 'Publish update', class:'btn btn-primary'%>
        <%= link_to  "Cancel", root_path, class:'btn btn-default' %>
       </div>
       <% end %>
    </div>
    <div class="col-md-1"></div>
</div>

app/views/posts/index.html.erb
<h2 class="page-header">
  <% if current_user%>
    <%= link_to  "Add post ", new_post_path, class:'btn btn-info' %>
  <% end %>
</h2>

<div class="row">
   <div class="col-md-10">
    <div class="recent-upload">
        <h4>RECENT HOTTEST NEWS TO READ</h4>
    </div>
      <div class="row">
        <% if @posts.exists? %>
            <% @posts.each do |post| %>
               <div class="col-md-4">
                  <div class="panel panel-default" >
                    <div class="panel panel-doby" id="post-index">
                      <%= link_to post_path(post) do %>
                          <h5><%=  raw post.title.truncate(50) %></h5>
                          <% if post.coverpicture.present? %>
                            <%= image_tag  "#{post.coverpicture}", width:'100%', height:'140px' %>
                          <% else %>
                            <%= image_tag  "img/image2.jpg", width:'100%', height:'140px' %>
                          <% end %>
                          <%= raw post.body.truncate(100)%><br>
                      <% end %>
                      <p>
                        <strong>Posted on: </strong><%= post.created_at.to_time.strftime('%b %e, %Y')%><br>
                        <strong>Posted by: </strong><%= post.user.name%>
                      </p>
                    </div>
                  </div> 
               </div>
            <% end%>
        <!-- pagination -->
        <% else %>
           <p>No post available!!</p>
        <% end %> 
      </div> 
  </div> 
  <div class="col-md-2" id="category">
        <% if @categories.exists%>
            <div class="panel panel-nfio">
                <div class="panel panel-heading">
                    <h4 >Categories</h4>
                </div>
                <div class="panel panel-body">
                   <% @categories.each do |category|%>
                        <li class="list-group-item"><%= link_to category.name, category_path(category), class:'glyphicon glyphicon-film'  %></li>
                    <%end%> 
                </div>
            </div>
        <%else%>
        <p>No categories found</p>
        <%end%>
    </div>
</div>

app/views/posts/new.html.erb
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
       <h2 class="page-header">
        <div class="recent-upload">
            <h4>ADD NEW POST</h4>
        </div>
       </h2>
       <%= form_for( @post) do |f| %>
       <% if @post.errors%>
        <% @post.errors.full_messages.each do |msg|%>
         <div class="alert alert-danger"><%= msg %></div>
        <%end%>
        <%end%>
       <div class="form-group">
           <%= f.label :title%>
           <%= f.text_field :title, class:'form-control'%>
       </div>
       <div class="form-group">
           <%= f.label :category%>
           <%= f.select :category_id, Category.order(:name).collect {|x|[x.name, x.id]}, {:include_blank => 'Select category'}, class:'form-control'%>
       </div>
       <div class="form-group">
           <%= f.text_field :user_id, class:'hidden', value:"#{current_user.id}"%>
       </div>
       <div class="form-group">
           <%= f.label :cover_picture, class:'glyphicon glyphicon-upload' %>
           <%= f.file_field :coverpicture, class:'form-control'%>
       </div>
        <div class="form-group">
           <%= f.label :body%>
           <%= f.cktext_area :body, class:'form-control'%>
       </div>
       <div class="form-group">
        <%= f.submit 'Publish new', class:'btn btn-primary'%>
        <%= link_to  "Cancel", posts_path, class:'btn btn-default' %>
       </div>
       <% end %>
    </div>
    <div class="col-md-1"></div>
</div>

app/views/posts/show.html.erb
<div class="row">
    <div class="col-md-1">
        
    </div>
    <div class="col-md-10">
        <div class="recent-upload">
            <h4><%= @post.title%></h4>
        </div>
        <div class="thumbnail">
           <%if @post.coverpicture.present?%>
           <%= image_tag  "#{@post.coverpicture}", width:'100%' %>
           <% else %> 
           <%= image_tag  "img/image2.jpg" %>
           <% end %> 
        </div>
        <div class="content">
            <%= raw @post.body %>
        </div>
        <div class="post-footer ">
            <p><strong>Category: </strong><%= link_to  @post.category.name, category_path(@post.category_id) %></p>
            <p><strong>Posted by: </strong><%= @post.user.name%></p>
            <p><strong>Posted on: </strong><%= @post.created_at.to_time.strftime('%A (%b %e, %Y at %H : %M %p)')%></p>
        </div>
        <% if current_user%>
        <% if @post.user_id == current_user.id%>
            <%= link_to  "Edit post ", edit_post_path(@post), class:'btn btn-info' %>
        <% end %>
        <% end %>
        <%= render  "partials/comments" %>
        <br/>
        <%= link_to  "Back", posts_path, class:'glyphicon glyphicon-arrow-left' %>
    </div>
    <div class="col-md-1">
        
    </div>
</div>