config/routes.rb
Rails.application.routes.draw do
  get 'services/index'
  get 'services/show'
  get 'about/index'
  mount Ckeditor::Engine => '/ckeditor'
  get 'types/show'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'comments/new'
  get 'categories/new'
  get 'categories/create'
  get 'categories/edit'
  get 'categories/update'
  get 'categories/index'
  get 'categories/show'
  get 'categories/destroy'
  devise_for :users
  get 'posts/new'
  get 'posts/create'
  get 'posts/edit'
  get 'posts/update'
  get 'posts/index'
  get 'posts/show'
  get 'posts/destroy'
  get 'videos/new'
  get 'videos/create'
  get 'videos/edit'
  get 'videos/update'
  get 'videos/index'
  get 'videos/show'
  get 'videos/destroy'
  get 'audios/new'
  get 'audios/create'
  get 'audios/edit'
  get 'audios/update'
  get 'audios/index'
  get 'audios/show'
  get 'audios/destroy'
  get 'contact' => 'contacts#new', :as => 'contact'
  get 'contacts/create'
  get 'about' => 'about#index', :as => 'about'
  get 'home' => 'home#index', as: 'home'

  resources :contacts, :audios, :videos, :posts, :categories, :comments, :services
  resources :types, only: [:show]

  resources :posts do
    resources :comments
  end
  root 'home#index'
  
  match "*path", to: "videos#catch_404", via: :all
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/audio.rb
class Audio < ApplicationRecord
  belongs_to :user
  belongs_to :type
  #validates picture to uplaod
  has_attached_file :coverpicture, styles: { medium: "300x300>", thumb: "100x100#" } #default_url: "/images/:style/missing.png"
  validates_attachment_content_type :coverpicture, content_type: /\Aimage\/.*\Z/

  #valides audios to upload
  has_attached_file :song_audio 
  validates_attachment :song_audio,
  :content_type => {:content_type => ["audio/mpeg", "audio/mp3"]},
  :file_type => {:matches => [/mp3\Z/]}

  validates_presence_of :title
  validates_presence_of :artist


  def self.search(query)
    where("artist like ? OR title like ?","%#{query}%", "%#{query}%")
end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts


    validates_uniqueness_of :name    
    validates_presence_of :name
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/contact.rb
class Contact < ApplicationRecord

    validates_presence_of :name
    validates_presence_of :email
    validates_presence_of :message
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :comments
    
    has_attached_file :coverpicture, styles: { medium: "300x300>", thumb: "100x100#" } #default_url: "/images/:style/missing.png"
    validates_attachment_content_type :coverpicture, content_type: /\Aimage/

    validates_presence_of :coverpicture
    validates_presence_of :title
    validates_presence_of :body

    def self.search(query)
        where("body like ? OR title like ?","%#{query}%", "%#{query}%")
    end
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :audios
    has_many :videos
    validates :name, presence: true, uniqueness: true
    
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/models/video.rb
class Video < ApplicationRecord
    belongs_to :user
    belongs_to :type

    validates_presence_of :song_title
    validates_presence_of :singer_name
    validates_presence_of :youtube_link
    validates_presence_of :song_title

    has_attached_file :coverpicture, styles: { medium: "300x300>", thumb: "100x100#" } #default_url: "/images/:style/missing.png"
    validates_attachment_content_type :coverpicture, content_type: /\Aimage\/.*\Z/
    def self.search(query)
        where("song_title like ? OR singer_name like ?","%#{query}%", "%#{query}%")
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Idarecords | <%= params[:controller] %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
   <nav class="navbar navbar-default navbar-fixed-top">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to image_tag("img/idarecords.jpg", width:'20%'), root_path, class:'navbar-brand' %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
        <%if current_user %>          
                <%= link_to  "Logout ", destroy_user_session_path, method: :delete, class:' navbar-btn navbar-right', id:'login' %>
              <% else%>
             <%= link_to  " Login ", new_user_session_path, class:'navbar-btn navbar-right', id:'login' %>
             <% end %>
          <ul class="nav navbar-nav">
            <li class="<%= params[:controller] == 'home' ? 'active' : ''%>"><%= link_to  "Home", root_path%></li>           
            <li class="<%= params[:controller] == 'about' ? 'active' : ''%>"><%= link_to  "About", about_path%></li>
            <li class="<%= params[:controller] == 'audios' ? 'active' : ''%>"><%= link_to  "Audios", audios_path%></li>
            <li class="<%= params[:controller] == 'videos' ? 'active' : ''%>"><%= link_to  "Videos", videos_path%></li>
            <li class="<%= params[:controller] == 'posts' ? 'active' : ''%>"><%= link_to  "Blog", posts_path%></li>
            
            <li class="<%= params[:controller] == 'services' ? 'active' : ''%>"><%= link_to  "Services", services_path%></li>
            <li class="<%= params[:controller] == 'contacts' ? 'active' : ''%>"><%= link_to  "Contact", contact_path%></li>
          </ul>

  </div>
                                 
        </div><!--/.nav-collapse -->
    </nav>
    <div class="container" id="container">
    <% if flash[:notice]%>
      <div class="alert alert-success"><%= flash[:notice]%></div>
    <% end %>
    <% if flash[:alert]%>
      <div class="alert alert-danger"><%= flash[:alert] %></div>
    <% end %>
      <%= render  "partials/search" %>

        <%= yield %>
    </div><!-- /.container -->
    
     <footer class="footer">
       &copy; copyright Idarecords 2019 | Alright reserved
 </body>
</html>

app/views/partials/_comments.html.erb
<div class="comments">
    <h3 class="page-header "><span class="badge"><%= @post.comments.length %></span> Comments</h3>
    <%@post.comments.each do |comment| %>
    <div class="comment">
        <div class="row">
            
            <div class="col-md-12">
                <div class="well">
                    
                    <h4><%= comment.name %></h4>
                    <%= comment.body%>
                    <br>
                    <br>
                    <strong>Commented by: </strong><%= comment.name%>
                    <br>
                    <strong>Commented on: </strong><%= comment.created_at.to_time.strftime('%b %e, %Y')%>
                </div>
            </div>
        </div>
    </div>
    <% end %>

    <div class="well add-comments">
       <h2 class="page-header">
          <a href="#collapse-3" data-toggle="collapse" data-parent="#accordion">
             Add Comment 
          </a>
       </h2> 
        <div id="collapse-3" class="panel-collapse collapse">            
        <%= form_for([@post, @post.comments.build]) do |f| %>
            <div class="form-group">
                <%= f.label :name%>
                <%= f.text_field :name, class:'form-control'%>
            </div>
            <div class="form-group">
                <%= f.label :email%> 
                <%= f.text_field :email, class:'form-control'%> 
            </div>
            <div class="form-group">
                <%= f.label :body %>
                <%= f.text_area :body, class:'form-control' %>
            </div>
            <%= f.submit "submit", class:'btn btn-success'%>
        <% end %>
        </div>
    </div>
</div>

app/views/partials/_search.html.erb
<%if params[:controller] == "posts"%>
  <%= form_tag(posts_index_path, :method => "get", id:"search-form", class:'form-inline pull-right') do %>
        <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder:"--Search posts--", class:'form-control'%>
        </div>
        <%= submit_tag "Search", :name => nil, class:'btn btn-success' %>
  <% end %>
  <% end %>
<% if params[:controller] == "audios"%>
   <%= form_tag(audios_index_path, :method => "get", id:"search-form", class:'form-inline pull-right') do %>
        <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder:"--Search Audios--", class:'form-control'%>
        </div>
        <%= submit_tag "Search", :name => nil, class:'btn btn-success' %>
   <% end %>
   <% end %>
<% if params[:controller] == "videos" %>
  <%= form_tag(videos_index_path, :method => "get", id:"search-form", class:'form-inline pull-right') do %>
        <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder:"--Search Videos--", class:'form-control'%>
        </div>
        <%= submit_tag "Search", :name => nil, class:'btn btn-success' %>
  <% end %>
<% end %>